import os
from typing import List, Optional

SUPPORTED_EXTENSIONS = {".py", ".c", ".cpp", ".sh", ".bash", ".js", ".ts"}

# Strict Ignore List (Excludes third-party junk, docs, binaries, assets)
IGNORED_DIRS = {
    "venv", ".venv", "env", ".git", "__pycache__", ".pytest_cache", 
    "node_modules", "build", "dist", ".idea", ".vscode", "vendor", 
    "third_party", "thirdparty", "deps", "external", "docs", ".github", 
    "site-packages", "benchmarks", "examples", "assets", "static", "packages"
}

MAX_FILE_SIZE_BYTES = 50 * 1024  # Skip files larger than 50KB (minified code / giant headers)
MAX_CORE_TARGETS = 30            # Professional Core File Sampling Cap


def scan_repository_for_targets(repo_path: str) -> List[str]:
    """
    Professional Core Sampler: Filters top 30 primary source files, 
    skipping minified bundles, assets, and third-party vendor trees.
    """
    target_files = []
    
    for root, dirs, files in os.walk(repo_path):
        dirs[:] = [d for d in dirs if d not in IGNORED_DIRS]
        
        # Max directory depth = 4
        depth = root.replace(repo_path, "").count(os.sep)
        if depth > 4:
            continue
            
        for file in files:
            ext = "." + file.split(".")[-1].lower() if "." in file else ""
            if ext in SUPPORTED_EXTENSIONS:
                if file.startswith("test_") or file.endswith("_test.py") or file.endswith(".test.js"):
                    continue
                    
                full_path = os.path.join(root, file)
                
                # Skip files > 50KB (autogenerated bundles / giant logs)
                try:
                    if os.path.getsize(full_path) > MAX_FILE_SIZE_BYTES:
                        continue
                except OSError:
                    continue
                    
                target_files.append(full_path)
                
                # Hard Cap at 30 Core Files for Professional Speed
                if len(target_files) >= MAX_CORE_TARGETS:
                    return target_files
                    
    return target_files


def find_test_file_for_target(repo_path: str, target_file_path: str) -> Optional[str]:
    """Smart Test Discovery across multiple languages."""
    base_name = os.path.splitext(os.path.basename(target_file_path))[0]
    possible_names = {
        f"test_{base_name}.py", f"{base_name}_test.py",
        f"test_{base_name}.sh", f"{base_name}_test.sh",
        f"{base_name}.test.js", f"{base_name}.test.ts"
    }

    for root, dirs, files in os.walk(repo_path):
        dirs[:] = [d for d in dirs if d not in IGNORED_DIRS]
        for file in files:
            if file in possible_names:
                return os.path.join(root, file)
                
    return None